#!/usr/bin/php
<?php        
        require_once('AWSSDKforPHP/sdk.class.php');

        $ec2 = new AmazonEC2();

        $response = $ec2->describe_instances();
        $ip = array();

        foreach ($response->body->reservationSet->item as $item) {
            $tags = array();

           if (isset($item->instancesSet->item->tagSet) and $item->instancesSet->item->instanceState->name == 'running') {

               $ip[] = (string)$item->instancesSet->item->privateIpAddress;
           }
       }

       print_r($ip);

